name: riff_switch
description: Experience seamless transitions and engaging interactions with RiffSwitch. 
  The switch library that empowers effortless sliding effects and captivating animations.
version: 0.0.4
homepage: https://github.com/kenresoft/riff_switch

environment:
  sdk: '>=3.4.1 <4.0.0'

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extensionresoft: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
# removing this line sets it to false;
# but this is also set to true in extensionresoft,
# and should be enable here too as it depends on the package.

