name: riff_switch
description: Experience seamless transitions and engaging interactions with RiffSwitch. 
  The switch library that empowers effortless sliding effects and captivating animations.
version: 0.0.3
homepage: https://github.com/kenresoft/riff_switch

environment:
  sdk: '>=3.0.0 <4.0.0'

  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# The following section is specific to Flutter packages.
flutter:

